<?php

return [

    'family_avatars' => [
        '🧑', '👩', '👨', '🧔', '👵', '👴', '👧', '👦',
        '🧑‍🦱', '👩‍🦰', '🧑‍🦳', '👩‍🦳',
    ],

    'dish_types' => [
        'Œufs' => '🍳',
        'Viande' => '🥩',
        'Salade' => '🥗',
        'Poisson' => '🐟',
        'Légumes' => '🥦',
        'Plat complet' => '🍽️',
        'Pâtes' => '🍝',
        'Dessert' => '🍰',
    ],

    'dish_type_default' => '🍴',

    'ingredients' => [
        'béchamel' => '🥣',
        'choucroute' => '🥬',
        'gateau' => '🍰',
        'gyozas' => '🥟',
        'lentilles' => '🫘',
        'mayonnaise' => '🥫',
        'moutarde' => '🥫',
        'nems' => '🌯',
        'nouilles chinoises' => '🍜',
        'pain' => '🍞',
        'pain à burger' => '🍔',
        'pain de mie' => '🍞',
        'pâte à flammekueche' => '🫓',
        'pâtes' => '🍝',
        'pâtes à lasagne' => '🍝',
        'riz' => '🍚',
        'riz ou semoule' => '🍚',
        'sauce tomate' => '🍅',
        'semoule' => '🌾',
        'comté' => '🧀',
        'crème aux œufs' => '🍮',
        'crème dessert' => '🍮',
        'crème fraîche' => '🥛',
        'feta' => '🧀',
        'fromage' => '🧀',
        'fromage râpé' => '🧀',
        'mozzarella' => '🧀',
        'œufs' => '🥚',
        'parmesan' => '🧀',
        'philadelphia' => '🧀',
        'ravioli' => '🥟',
        'tofu' => '🥡',
        'Yaourt fruit' => '🥣',
        'Yaourt nature' => '🥣',
        'Yaourt soja' => '🥣',
        'ail' => '🧄',
        'aubergines' => '🍆',
        'avocat' => '🥑',
        'brocolis' => '🥦',
        'carottes' => '🥕',
        'champignons' => '🍄',
        'chou-fleur' => '🥦',
        'citron' => '🍋',
        'concombre' => '🥒',
        'courgettes' => '🥒',
        'endives' => '🥬',
        'épinards' => '🥬',
        'fruits frais' => '🍎',
        'haricots verts' => '🫛',
        'légumes variés' => '🥗',
        'melon' => '🍈',
        'menthe' => '🌿',
        'oignons' => '🧅',
        'persil' => '🌿',
        'petits pois' => '🫛',
        'poireaux' => '🥬',
        'poivrons' => '🫑',
        'pommes de terre' => '🥔',
        'salade romaine' => '🥬',
        'salade verte' => '🥬',
        'Salade de fruits' => '🍓',
        'tomates' => '🍅',
        'cabillaud' => '🐟',
        'calamars ou seiches' => '🦑',
        'crevettes' => '🍤',
        'escalope de dinde' => '🦃',
        'jambon' => '🍖',
        'lardons' => '🥓',
        'poisson blanc' => '🐟',
        'poisson pané' => '🐟',
        'poulet' => '🍗',
        'rôti de bœuf' => '🥩',
        'rôti de porc' => '🥩',
        'saumon' => '🐟',
        'saumon ou truite fumé' => '🐟',
        'seiches' => '🦑',
        'steak haché' => '🥩',
        'viande hachée' => '🥩',
    ],

    'ingredient_category_default' => [
        'Épicerie (sec, conserves, pain)' => '🥫',
        'Frais (laitages, œufs, fromage)' => '🧀',
        'Fruits & légumes' => '🥦',
        'Viande & poisson' => '🍖',
    ],

    'ingredient_default' => '🍴',

];
